name = "Sikh Sacred Music"
license = "MIT"
licenselink = "https://github.com/letItCurl/minimal_marketing/blob/main/LICENSE"
description = "Learn Sikh scared music and take exams"
version = "0.0.1"

homepage = "https://sikhsacredmusic.org"

tags = ["music", "sikh", "strings", "exam"]
features = ["tailwind", "form", "CTA", "Google analytics"]

[author]
    name = "Jujhar Singh"
    homepage = "https://jujhar.com"

[original]
  name = "Hugo-Tailwind-3.1"
  author = "4044ever"
  homepage = "https://github.com/4044ever"
  repo = "https://github.com/4044ever/Hugo-Tailwind-3.1"
